version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: payslip_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: employee_payslip
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: payslip_backend
    ports:
      - "3005:3005"
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin234
      DB_NAME: employee_payslip
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 3005

  employee_payslip:
    build: ./Employee_Payslip
    container_name: payslip_employee_ui
    ports:
      - "8010:80"
    depends_on:
      - backend

  hr_payslip:
    build: ./HR_Payslip
    container_name: payslip_hr_ui
    ports:
      - "8011:80"
    depends_on:
      - backend

volumes:
  pgdata:

